# version is optional, but it is good practice to pin the version
version: v0.13.0

dsn: sqlite:///tmp/kratos.db?_fk=true

serve:
  public:
    base_url: http://localhost:4433/
  admin:
    base_url: http://localhost:4434/

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file://./kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/

  flows:
    error:
      ui_url: http://localhost:3000/error

    registration:
      ui_url: http://localhost:3000/registration

courier:
  smtp:
    connection_uri: smtps://localhost:1025/?skip_ssl_verify=true
